<?php

/**
 * @file
 * Contains hooks for custom list default.
 */

use Drupal\views\ViewExecutable;

/**
 * Implements @see hook_views_post_execute().
 */
function custom_list_default_views_post_execute(ViewExecutable $view) {
  if (empty($view->result)) {
    return;
  }

  // Handle uniques only relevant for this styles provided by this module.
  if ($view->getStyle()->getPluginId() !== 'custom_list_default') {
    return;
  }

  /** @var \Drupal\custom_list\Plugin\views\style\CustomListBase $style_plugin */
  $style_plugin = $view->getStyle();
  if (!$style_plugin->usesUniqueEntities()) {
    return;
  }

  $entities = [];
  foreach ($view->result as $row) {
    if (!empty($row->_entity)) {
      $entities[] = $row->_entity;
    }
  }

  /** @var \Drupal\custom_list\UniqueEntitiesStorageInterface $unique_storage */
  $unique_storage = \Drupal::service('custom_list.unique_entities_store');

  /** @var \Drupal\views\ViewEntityInterface $view_storage */
  $view_storage = $view->storage;

  $unique_storage->setIds($view_storage->get('base_table'), $view_storage->get('base_field'), $entities);
}
